export const Index = '/pages/index/index'//登录首页
export const Activity = '/pages/index/activity'// 活动页面
export const Mine = '/pages/index/mine'// 我的页面
export const BarList = '/pages/barList/index'// 酒吧列表页面
export const BarDetail = '/pages/barDetail/index'// 酒吧详情页
export const ActivityDetail = '/pages/activityDetail/index'// 活动详情页
export const Booking = '/pages/booking/index'// 酒吧预订页
export const BookingActivity = '/pages/bookingActivity/index'// 活动预订选择桌位预订页面
export const BookOrder = '/pages/bookOrder/index'// 我的预订
export const ActivityOrder = '/pages/activityOrder/index'// 我的活动
export const EditPhone = '/pages/editPhone/index'// 换绑手机号
export const Collect = '/pages/collect/index'// 我的收藏
export const Search = '/pages/search/index'// 搜索
export const Setting = '/pages/setting/index'// 授权页面
export const Protocol = '/pages/protocol/protocol'// 用户协议页面
export const Buy = '/pages/buy/buy'// 确认订单页